---
- name: install dependency package (inotify-tools)
  yum: name=inotify-tools-devel state=present

- name: verify hex installation
  command: mix hex.info
  sudo: no
  register: which_hex
  failed_when: which_hex.rc not in [0, 1]

- name: install hex (mix) package
  shell: yes | mix local.hex
  sudo: no
  when: which_hex.rc == 1

- name: verify phoenix installation
  command: mix phoenix.new --version
  sudo: no
  register: which_phoenix
  failed_when: which_phoenix.rc not in [0, 1]

- name: install phoenix framework (mix) package
  shell: yes | mix archive.install {{ phoenix_framework.installer }}
  sudo: no
  when: which_phoenix.rc == 1