---
- name: popular software programs
  yum: name={{ item }} state=present
  with_items: common.popular_packages
  when: common.popular_packages is defined

# for Japan
- name: ntp server (chronyd)
  yum: name=chrony state=present

- name: delete existing settings
  lineinfile: dest=/etc/chrony.conf regexp="^server.+?cent" state=absent
  when: common.ntp_config.enabled

- name: server settings
  lineinfile: dest=/etc/chrony.conf line="server {{ item }} iburst"
  with_items: common.ntp_config.servers
  notify: restart service (chronyd)
  when: common.ntp_config.enabled

- name: start service (chronyd)
  service: name=chronyd state=started enabled=yes

- name: use local time
  file: >
         src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link
         force=yes

- name: hardware > system time
  # http://blog.livedoor.jp/hakin/archives/22700821.html
  command: /usr/sbin/hwclock --hctosys --localtime