version: '2'
services:
  cuenta-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: cuenta_dev
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - cuenta:/var/lib/mysql
    networks:
      - neeco
  cuenta-application:
    image: registry.neec.xyz/dev/cuenta-application:latest
    environment:
      CUENTA_PORT: 4000
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER: root
      CUENTA_DATABASE_PASSWORD: root
      IMAGEN_URL: http://imagen-application:8000/
      KONG_URL: http://kong-application:8001/
      OLVIDO_URL: http://olvido-application:8001/
      STATIC_IMAGE_URL: http://localhost/
      MIX_ENV: dev
    depends_on:
      - cuenta-database
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - neeco

volumes:
  cuenta:
    driver: local

networks:
  neeco:
    external:
      name: neeco_develop
