FROM registry.neec.xyz/neeco/elixir:1.3.4
ENV MIX_ENV=dev
RUN apk add --no-cache --update mariadb-client && \
    apk add --no-cache --virtual build-dependencies \
    gcc \
    make \
    libc-dev \
    libgcc \
    less \
    curl && \
    mix do local.hex --force, local.rebar --force
COPY mix.exs /app/mix.exs
COPY mix.lock /app/mix.lock
WORKDIR /app
RUN mix deps.get
RUN mix compile
CMD ["ash"]
