version: '2'
services:
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
    - cuenta:/var/lib/mysql
  application:
    build: .
    image: cuenta-application
    environment:
      - CUENTA_PORT=4000
      - CUENTA_DATABASE_HOST=database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - CUENTA_KONG_URL=http://kong-application:8001
      - CUENTA_IMAGE_URL=http://localhost
    ports:
      - "4000:4000"
    depends_on:
      - database
volumes:
  cuenta:
    external:
      name: neeco_cuenta
