version: '2'
services:
  cuenta-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - cuenta:/var/lib/mysql
    networks:
      - cuenta
  cuenta-application:
    build: .
    image: cuenta-application
    environment:
      - CUENTA_PORT=4000
      - CUENTA_DATABASE_HOST=cuenta-database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - CUENTA_KONG_URL=http://kong-application:8001
      - CUENTA_IMAGE_URL=http://localhost
    depends_on:
      - cuenta-database
    volumes:
      - public:/app/uploads
    networks:
      - cuenta
      - kong-cuenta

volumes:
  cuenta:
    external:
      name: neeco_cuenta
  public:
    external:
      name: neeco_public

networks:
  cuenta:
    external:
      name: neeco_cuenta
  kong-cuenta:
    external:
      name: neeco_kong-cuenta
