version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql
      - /app/log
  db:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=y
    ports:
      - "13306:3306"
    volumes_from:
      - datastore
  web:
    build: .
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes_from:
      - datastore
